<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArOrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ar_orders')->delete();
        
        \DB::table('ar_orders')->insert(array (
            0 => 
            array (
                'agency' => NULL,
                'cancel_reason' => NULL,
                'cancel_status' => NULL,
                'canceled_by' => NULL,
                'code' => '67d5389924266',
                'comeback' => 0,
                'cooler' => 0,
                'created_at' => '2025-03-15 08:51:45',
                'date_reserve' => NULL,
                'delivery_id' => 13,
                'destination_address' => 'استان تهران، تهران، منطقه ۱۰، کوچه بیات، M9R6+HP6، إيران',
                'destination_lat' => '35.69146839763842',
                'destination_long' => '51.36191613972187',
                'discounted_price' => 31000.0,
                'driver' => 1,
                'driver_rate' => NULL,
                'economic' => 0,
                'helper' => 0,
                'hurry' => 0,
                'hurry_percent' => '0',
                'id' => 1,
                'mobile' => '09104992005',
                'name' => 'shayan',
                'net_price' => 24800.0,
                'origin_address' => 'M978+RFP منطقه ۱۷، تهران، استان تهران، إيران',
                'origin_lat' => '35.6646273',
                'origin_long' => '51.3663009',
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'pay_side' => 'الانطلاق',
                'pay_type' => 1,
                'percent_code' => NULL,
                'percent_discount' => 0.0,
                'price' => 31000.0,
                'private' => 0,
                'rate' => NULL,
                'report_id' => 200193,
                'reserve' => 0,
                'sort' => 1742026905148000000,
                'state' => 6,
                'stop_minutes' => NULL,
                'stop_minutes2' => NULL,
                'stop_time' => NULL,
                'stop_time2' => NULL,
                'time_reserve' => NULL,
                'updated_at' => '2025-03-15 09:46:58',
                'user' => 1,
                'user_rate' => 1,
            ),
            1 => 
            array (
                'agency' => NULL,
                'cancel_reason' => NULL,
                'cancel_status' => NULL,
                'canceled_by' => NULL,
                'code' => '67d55bc880a38',
                'comeback' => 0,
                'cooler' => 0,
                'created_at' => '2025-03-15 11:21:52',
                'date_reserve' => NULL,
                'delivery_id' => 13,
                'destination_address' => '8CJ3+H2H، بغداد، بغداد محافظة، العراق',
                'destination_lat' => '33.33145510942044',
                'destination_long' => '44.40257228403668',
                'discounted_price' => 13000.0,
                'driver' => 1,
                'driver_rate' => NULL,
                'economic' => 0,
                'helper' => 0,
                'hurry' => 0,
                'hurry_percent' => '0',
                'id' => 4,
                'mobile' => '09900733439',
                'name' => 'تست',
                'net_price' => 10400.0,
                'origin_address' => '110 شارع الصالحية، بغداد،، بغداد،، بغداد، بغداد محافظة، العراق',
                'origin_lat' => '33.32263204376783',
                'origin_long' => '44.39426816492657',
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'pay_side' => 'الانطلاق',
                'pay_type' => 1,
                'percent_code' => NULL,
                'percent_discount' => 0.0,
                'price' => 13000.0,
                'private' => 0,
                'rate' => NULL,
                'report_id' => 200451,
                'reserve' => 0,
                'sort' => 1742035912526800000,
                'state' => 6,
                'stop_minutes' => NULL,
                'stop_minutes2' => 120.0,
                'stop_time' => NULL,
                'stop_time2' => '2 ساعت',
                'time_reserve' => NULL,
                'updated_at' => '2025-03-17 11:27:20',
                'user' => 2,
                'user_rate' => 1,
            ),
            2 => 
            array (
                'agency' => NULL,
                'cancel_reason' => NULL,
                'cancel_status' => NULL,
                'canceled_by' => NULL,
                'code' => '67d8005ab91ae',
                'comeback' => 0,
                'cooler' => 0,
                'created_at' => '2025-03-17 11:28:34',
                'date_reserve' => '2025-03-18',
                'delivery_id' => 13,
                'destination_address' => '8976+4HH، بغداد، بغداد محافظة، العراق',
                'destination_lat' => '33.312804980653006',
                'destination_long' => '44.361488074064255',
                'discounted_price' => 5000.0,
                'driver' => 1,
                'driver_rate' => NULL,
                'economic' => 0,
                'helper' => 0,
                'hurry' => 0,
                'hurry_percent' => '0',
                'id' => 15,
                'mobile' => '07729633336',
                'name' => 'علی',
                'net_price' => 4000.0,
                'origin_address' => '8976+4HH، بغداد، بغداد محافظة، العراق',
                'origin_lat' => '33.312804980653006',
                'origin_long' => '44.361488074064255',
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'pay_side' => 'الانطلاق',
                'pay_type' => 1,
                'percent_code' => NULL,
                'percent_discount' => 0.0,
                'price' => 5000.0,
                'private' => 0,
                'rate' => NULL,
                'report_id' => 200516,
                'reserve' => 1,
                'sort' => 1742209114758100000,
                'state' => 6,
                'stop_minutes' => NULL,
                'stop_minutes2' => NULL,
                'stop_time' => NULL,
                'stop_time2' => NULL,
                'time_reserve' => '17:48',
                'updated_at' => '2025-03-17 11:31:14',
                'user' => 3,
                'user_rate' => 1,
            ),
            3 => 
            array (
                'agency' => NULL,
                'cancel_reason' => 1,
                'cancel_status' => 'تم الإلغاء',
                'canceled_by' => 'علی',
                'code' => '67d800a542e00',
                'comeback' => 0,
                'cooler' => 0,
                'created_at' => '2025-03-17 11:29:49',
                'date_reserve' => NULL,
                'delivery_id' => 13,
                'destination_address' => '8976+4HH، بغداد، بغداد محافظة، العراق',
                'destination_lat' => '33.312804980653006',
                'destination_long' => '44.361488074064255',
                'discounted_price' => 5000.0,
                'driver' => 1,
                'driver_rate' => NULL,
                'economic' => 0,
                'helper' => 0,
                'hurry' => 0,
                'hurry_percent' => '0',
                'id' => 16,
                'mobile' => '07729633336',
                'name' => 'علی',
                'net_price' => NULL,
                'origin_address' => '8976+4HH، بغداد، بغداد محافظة، العراق',
                'origin_lat' => '33.312804980653006',
                'origin_long' => '44.361488074064255',
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'pay_side' => 'الانطلاق',
                'pay_type' => 1,
                'percent_code' => NULL,
                'percent_discount' => 0.0,
                'price' => 5000.0,
                'private' => 0,
                'rate' => NULL,
                'report_id' => 200530,
                'reserve' => 0,
                'sort' => 1742209189273800000,
                'state' => 7,
                'stop_minutes' => NULL,
                'stop_minutes2' => NULL,
                'stop_time' => NULL,
                'stop_time2' => NULL,
                'time_reserve' => NULL,
                'updated_at' => '2025-03-17 11:32:50',
                'user' => 3,
                'user_rate' => 0,
            ),
            4 => 
            array (
                'agency' => NULL,
                'cancel_reason' => NULL,
                'cancel_status' => NULL,
                'canceled_by' => NULL,
                'code' => '67d8238767afb',
                'comeback' => 0,
                'cooler' => 0,
                'created_at' => '2025-03-17 13:58:39',
                'date_reserve' => NULL,
                'delivery_id' => 13,
                'destination_address' => 'VH3C+43 خالص، العراق',
                'destination_lat' => '33.852866075290464',
                'destination_long' => '44.57022126764059',
                'discounted_price' => 188000.0,
                'driver' => NULL,
                'driver_rate' => NULL,
                'economic' => 0,
                'helper' => 0,
                'hurry' => 1,
                'hurry_percent' => '20',
                'id' => 18,
                'mobile' => '07805754917',
                'name' => 'كاظم بربر',
                'net_price' => NULL,
                'origin_address' => '994Q+JX7، بغداد، بغداد محافظة، العراق',
                'origin_lat' => '33.35655554690612',
                'origin_long' => '44.390023089945316',
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'pay_side' => 'الانطلاق',
                'pay_type' => 1,
                'percent_code' => NULL,
                'percent_discount' => 0.0,
                'price' => 225600.0,
                'private' => 0,
                'rate' => NULL,
                'report_id' => 200555,
                'reserve' => 0,
                'sort' => 1742218119424600000,
                'state' => 1,
                'stop_minutes' => NULL,
                'stop_minutes2' => NULL,
                'stop_time' => NULL,
                'stop_time2' => NULL,
                'time_reserve' => NULL,
                'updated_at' => '2025-03-17 13:58:45',
                'user' => 4,
                'user_rate' => 0,
            ),
        ));
        
        
    }
}