<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArDriversTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('ar_drivers')->delete();
        
        \DB::table('ar_drivers')->insert(array (
            0 => 
            array (
                'agency' => NULL,
                'car_detail' => 1,
                'car_model' => NULL,
                'car_tag' => NULL,
                'certificat_date' => '2025-03-15',
                'certificate_type' => 3,
                'certificate_validity' => '12',
                'code' => 'p732786',
                'code_meli' => '0918494646',
                'created_at' => '2025-03-15 08:18:04',
                'credit' => -9800.0,
                'description' => NULL,
                'family_number' => '09140999200',
                'fcm_token' => 'eThLDSQFT7mmtJKoyTqMMB:APA91bGFAGuZj6vwe95-Zayg2F-H2xTTV2daCC5JCdlk1xtHkhX3ruIfe2UmHu1HibA6lT7_9DkMzLxoewK1MENTt-v7sUBYCfsal4NYIQfzdLlBF0OEewg',
                'gender' => 1,
                'has_car_details' => 0,
                'has_documents' => 0,
                'has_info_bank' => 0,
                'has_info_user' => 0,
                'has_profile' => 0,
                'id' => 1,
                'image' => 'drivers/image/1742026798.jpeg',
                'intro_code' => NULL,
                'lat' => '32.6890418',
                'level' => 3,
                'long' => '51.6536286',
                'mobile' => '9104992005',
                'name' => 'shayan',
                'notif_token' => '67d530b405d97',
                'number_licence' => NULL,
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'report_id' => 200529,
                'sort' => 1742024884023100000,
                'state' => 1,
                'state_approval' => 2,
                'type_activity' => 13,
                'updated_at' => '2025-03-17 11:32:14',
                'verify_agency' => NULL,
                'verify_code' => '',
            ),
            1 => 
            array (
                'agency' => NULL,
                'car_detail' => 2,
                'car_model' => NULL,
                'car_tag' => NULL,
                'certificat_date' => '2025-03-02',
                'certificate_type' => 3,
                'certificate_validity' => '1',
                'code' => 'p305869',
                'code_meli' => '123456',
                'created_at' => '2025-03-15 23:56:40',
                'credit' => NULL,
                'description' => NULL,
                'family_number' => '07726366663',
                'fcm_token' => 'dghu_cJtTRqRyvYFK5K3mJ:APA91bGbZ7IQITWIUiO3FSE02WGj2yBFzWEQqykDnHa1nbsfOaEOY2KE-5KAWcn3j6qjWTiF0CnM8KBXw6eMbvlyGMMn5w0dvW3hwJYvG_FrvCIWPnz5IOc',
                'gender' => 2,
                'has_car_details' => 0,
                'has_documents' => 0,
                'has_info_bank' => 0,
                'has_info_user' => 0,
                'has_profile' => 0,
                'id' => 2,
                'image' => 'drivers/image/1742081291.jpeg',
                'intro_code' => NULL,
                'lat' => NULL,
                'level' => 3,
                'long' => NULL,
                'mobile' => '0772963336',
                'name' => 'علي',
                'notif_token' => '67d60cb0828f9',
                'number_licence' => NULL,
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'report_id' => 200292,
                'sort' => 1742081200534000000,
                'state' => 1,
                'state_approval' => 2,
                'type_activity' => 16,
                'updated_at' => '2025-03-16 00:06:02',
                'verify_agency' => NULL,
                'verify_code' => NULL,
            ),
            2 => 
            array (
                'agency' => NULL,
                'car_detail' => NULL,
                'car_model' => NULL,
                'car_tag' => NULL,
                'certificat_date' => NULL,
                'certificate_type' => NULL,
                'certificate_validity' => NULL,
                'code' => 'p992826',
                'code_meli' => NULL,
                'created_at' => '2025-03-17 10:06:05',
                'credit' => NULL,
                'description' => NULL,
                'family_number' => NULL,
                'fcm_token' => 'eThLDSQFT7mmtJKoyTqMMB:APA91bGFAGuZj6vwe95-Zayg2F-H2xTTV2daCC5JCdlk1xtHkhX3ruIfe2UmHu1HibA6lT7_9DkMzLxoewK1MENTt-v7sUBYCfsal4NYIQfzdLlBF0OEewg',
                'gender' => NULL,
                'has_car_details' => 0,
                'has_documents' => 0,
                'has_info_bank' => 0,
                'has_info_user' => 0,
                'has_profile' => 0,
                'id' => 3,
                'image' => NULL,
                'intro_code' => NULL,
                'lat' => NULL,
                'level' => NULL,
                'long' => NULL,
                'mobile' => '07729633336',
                'name' => NULL,
                'notif_token' => '67d7ed054b52f',
                'number_licence' => NULL,
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'report_id' => 200425,
                'sort' => 1742204165308000000,
                'state' => 0,
                'state_approval' => NULL,
                'type_activity' => NULL,
                'updated_at' => '2025-03-17 11:25:51',
                'verify_agency' => NULL,
                'verify_code' => '',
            ),
            3 => 
            array (
                'agency' => NULL,
                'car_detail' => NULL,
                'car_model' => NULL,
                'car_tag' => NULL,
                'certificat_date' => NULL,
                'certificate_type' => NULL,
                'certificate_validity' => NULL,
                'code' => 'p116640',
                'code_meli' => NULL,
                'created_at' => '2025-03-17 10:07:37',
                'credit' => NULL,
                'description' => NULL,
                'family_number' => NULL,
                'fcm_token' => NULL,
                'gender' => NULL,
                'has_car_details' => 0,
                'has_documents' => 0,
                'has_info_bank' => 0,
                'has_info_user' => 0,
                'has_profile' => 0,
                'id' => 4,
                'image' => NULL,
                'intro_code' => NULL,
                'lat' => NULL,
                'level' => NULL,
                'long' => NULL,
                'mobile' => '07729366663',
                'name' => NULL,
                'notif_token' => '67d7ed61eed3b',
                'number_licence' => NULL,
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'report_id' => 200385,
                'sort' => 1742204257977500000,
                'state' => 0,
                'state_approval' => NULL,
                'type_activity' => NULL,
                'updated_at' => '2025-03-17 10:07:37',
                'verify_agency' => NULL,
                'verify_code' => '165433',
            ),
            4 => 
            array (
                'agency' => NULL,
                'car_detail' => 3,
                'car_model' => 'بنز',
                'car_tag' => '754fd',
                'certificat_date' => '2025-03-11',
                'certificate_type' => 3,
                'certificate_validity' => '20',
                'code' => 'p756047',
                'code_meli' => '1234567890',
                'created_at' => '2025-03-18 05:48:32',
                'credit' => NULL,
                'description' => NULL,
                'family_number' => '09900733439',
                'fcm_token' => 'cF1ocE-WQcetDnX6Vyjkmk:APA91bFg6o9mDj9zmzFfH1pIixBNIsQCHXeSubjIXkuUOwAZVhBqzu_xIAo7P8TB3DY6M7-mqSjmQQ77N7WwkMovcWJ8OhI1oVZRJDjJ7nhECK6ENXmBn_g',
                'gender' => 2,
                'has_car_details' => 0,
                'has_documents' => 0,
                'has_info_bank' => 0,
                'has_info_user' => 0,
                'has_profile' => 0,
                'id' => 5,
                'image' => 'drivers/image/1742275187.jpeg',
                'intro_code' => NULL,
                'lat' => NULL,
                'level' => 3,
                'long' => NULL,
                'mobile' => '09900733439',
                'name' => 'تست',
                'notif_token' => '67d90228bcd2c',
                'number_licence' => NULL,
                'parent_id' => NULL,
                'parent_slug' => NULL,
                'report_id' => 200587,
                'sort' => 1742275112772900000,
                'state' => 1,
                'state_approval' => 1,
                'type_activity' => 16,
                'updated_at' => '2025-03-18 05:50:36',
                'verify_agency' => NULL,
                'verify_code' => NULL,
            ),
        ));
        
        
    }
}