<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('categories')->delete();
        
        \DB::table('categories')->insert(array (
            0 => 
            array (
                'created_at' => '2023-12-20 06:23:15',
                'icon' => NULL,
                'id' => 1,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'users',
                'sort' => 1703062395,
                'title' => 'کاربران',
                'updated_at' => '2024-05-07 08:48:09',
            ),
            1 => 
            array (
                'created_at' => '2023-12-20 06:23:30',
                'icon' => NULL,
                'id' => 2,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'orders',
                'sort' => 1703337810,
                'title' => 'سفرها',
                'updated_at' => '2024-07-31 11:31:28',
            ),
            2 => 
            array (
                'created_at' => '2023-12-20 06:43:26',
                'icon' => NULL,
                'id' => 6,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'deliveries',
                'sort' => 1703339490,
                'title' => 'سرویس ها',
                'updated_at' => '2023-12-24 04:13:26',
            ),
            3 => 
            array (
                'created_at' => '2023-12-20 07:50:23',
                'icon' => NULL,
                'id' => 7,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'favorite_place',
                'sort' => 1703067623,
                'title' => 'مکان های منتخب',
                'updated_at' => '2023-12-31 03:40:14',
            ),
            4 => 
            array (
                'created_at' => '2023-12-20 08:12:50',
                'icon' => NULL,
                'id' => 9,
                'is_menu' => 1,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'order_items',
                'sort' => 1703340888,
            'title' => 'آیتم های مرسوله (موتور باکس)',
                'updated_at' => '2023-12-24 06:03:47',
            ),
            5 => 
            array (
                'created_at' => '2023-12-20 08:16:40',
                'icon' => NULL,
                'id' => 10,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '9',
                'slug' => 'type_parcel',
                'sort' => 1703069200,
                'title' => 'نوع مرسوله',
                'updated_at' => '2024-04-22 08:03:31',
            ),
            6 => 
            array (
                'created_at' => '2023-12-20 09:34:25',
                'icon' => NULL,
                'id' => 11,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'stop_on_way',
                'sort' => 1703073865,
                'title' => 'اطلاعات توقف در محل',
                'updated_at' => '2023-12-24 07:58:05',
            ),
            7 => 
            array (
                'created_at' => '2023-12-23 04:42:14',
                'icon' => NULL,
                'id' => 12,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'slider',
                'sort' => 1703400062,
                'title' => 'اسلایدر',
                'updated_at' => '2024-08-31 08:47:50',
            ),
            8 => 
            array (
                'created_at' => '2023-12-23 10:53:30',
                'icon' => NULL,
                'id' => 13,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'stop_on_way',
                'sort' => 1703346465,
                'title' => 'آیتم های توقف در محل',
                'updated_at' => '2023-12-24 07:58:32',
            ),
            9 => 
            array (
                'created_at' => '2023-12-23 11:03:09',
                'icon' => NULL,
                'id' => 14,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'status',
                'sort' => 1703338389,
                'title' => 'وضعیت',
                'updated_at' => '2023-12-24 03:15:38',
            ),
            10 => 
            array (
                'created_at' => '2023-12-23 11:13:58',
                'icon' => NULL,
                'id' => 15,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'pay_typs',
                'sort' => 1703339038,
                'title' => 'روش های پرداخت',
                'updated_at' => '2024-02-19 06:45:34',
            ),
            11 => 
            array (
                'created_at' => '2023-12-23 11:21:30',
                'icon' => NULL,
                'id' => 16,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'drivers',
                'sort' => 1703062410,
                'title' => 'رانندگان',
                'updated_at' => '2024-05-07 08:47:58',
            ),
            12 => 
            array (
                'created_at' => '2023-12-23 11:44:48',
                'icon' => NULL,
                'id' => 17,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'wait_service',
                'sort' => 1703346008,
                'title' => 'آیتم های صفحه انتظار سرویس',
                'updated_at' => '2023-12-24 05:56:22',
            ),
            13 => 
            array (
                'created_at' => '2023-12-23 13:08:03',
                'icon' => NULL,
                'id' => 19,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'cancel_trip',
                'sort' => 1703345883,
                'title' => 'دلایل لغو سفر',
                'updated_at' => '2024-02-03 11:54:52',
            ),
            14 => 
            array (
                'created_at' => '2023-12-23 13:09:00',
                'icon' => NULL,
                'id' => 20,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'cancel_request',
                'sort' => 1703345940,
            'title' => 'دلایل لغو درخواست (پیش از قبول راننده)',
                'updated_at' => '2023-12-24 06:02:49',
            ),
            15 => 
            array (
                'created_at' => '2023-12-23 13:10:08',
                'icon' => NULL,
                'id' => 21,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'wallet',
                'sort' => 1703063606,
                'title' => 'کیف پول',
                'updated_at' => '2023-12-24 06:30:41',
            ),
            16 => 
            array (
                'created_at' => '2023-12-23 13:17:45',
                'icon' => NULL,
                'id' => 22,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'cost_type',
                'sort' => 1703315534,
                'title' => 'نوع هزینه',
                'updated_at' => '2023-12-24 03:16:07',
            ),
            17 => 
            array (
                'created_at' => '2023-12-24 02:03:27',
                'icon' => NULL,
                'id' => 23,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'heavy_equipment',
                'sort' => 1703392407,
                'title' => 'وسایل سنگین',
                'updated_at' => '2023-12-24 02:03:27',
            ),
            18 => 
            array (
                'created_at' => '2023-12-24 03:15:03',
                'icon' => NULL,
                'id' => 25,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '9',
                'slug' => 'price_parcel',
                'sort' => 1703396703,
                'title' => 'ارزش مرسوله',
                'updated_at' => '2023-12-24 03:15:03',
            ),
            19 => 
            array (
                'created_at' => '2023-12-24 03:39:06',
                'icon' => NULL,
                'id' => 26,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '31',
                'slug' => 'order_motor_details',
                'sort' => 1703398146,
                'title' => 'جزئیات سفارشات موتور باکس',
                'updated_at' => '2023-12-24 04:11:40',
            ),
            20 => 
            array (
                'created_at' => '2023-12-24 03:49:30',
                'icon' => NULL,
                'id' => 29,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'price_floors',
                'sort' => 1703398770,
                'title' => 'تحديد سعر الطوابق',
                'updated_at' => '2024-09-18 07:13:14',
            ),
            21 => 
            array (
                'created_at' => '2023-12-24 03:58:50',
                'icon' => NULL,
                'id' => 30,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'worker_price',
                'sort' => 1703399330,
                'title' => 'تعیین قیمت هر کارگر باربری',
                'updated_at' => '2023-12-24 03:58:50',
            ),
            22 => 
            array (
                'created_at' => '2023-12-24 04:11:02',
                'icon' => NULL,
                'id' => 31,
                'is_menu' => 1,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'orders_menu',
                'sort' => 1703068970,
                'title' => 'جزئیات سفارشات',
                'updated_at' => '2023-12-24 04:13:59',
            ),
            23 => 
            array (
                'created_at' => '2023-12-24 04:58:37',
                'icon' => NULL,
                'id' => 32,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '31',
                'slug' => 'moving_order_details',
                'sort' => 1703402917,
                'title' => 'جزئیات سفارشات اثاث کشی',
                'updated_at' => '2023-12-24 04:58:37',
            ),
            24 => 
            array (
                'created_at' => '2023-12-24 06:20:52',
                'icon' => NULL,
                'id' => 33,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'path_info',
                'sort' => 1703407852,
                'title' => 'اطلاعات مسیر',
                'updated_at' => '2023-12-24 06:20:52',
            ),
            25 => 
            array (
                'created_at' => '2023-12-28 02:46:28',
                'icon' => NULL,
                'id' => 34,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'way_type',
                'sort' => 1703740588,
                'title' => 'نوع مسیر',
                'updated_at' => '2023-12-28 02:48:43',
            ),
            26 => 
            array (
                'created_at' => '2024-01-07 08:14:53',
                'icon' => NULL,
                'id' => 35,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'statuses',
                'sort' => 1704624293,
                'title' => 'وضعیت ها',
                'updated_at' => '2024-01-07 08:14:53',
            ),
            27 => 
            array (
                'created_at' => '2024-01-08 09:28:28',
                'icon' => NULL,
                'id' => 36,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'car_details',
                'sort' => 1704715108,
                'title' => 'مشخصات ماشین',
                'updated_at' => '2024-01-08 09:28:28',
            ),
            28 => 
            array (
                'created_at' => '2024-01-09 02:12:05',
                'icon' => NULL,
                'id' => 37,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'documents',
                'sort' => 1704775325,
                'title' => 'مدارک راننده',
                'updated_at' => '2024-01-09 02:12:05',
            ),
            29 => 
            array (
                'created_at' => '2024-01-09 02:20:45',
                'icon' => NULL,
                'id' => 38,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '39',
                'slug' => 'car_models',
                'sort' => 1704775845,
                'title' => 'مدل های ماشین',
                'updated_at' => '2024-01-09 03:10:46',
            ),
            30 => 
            array (
                'created_at' => '2024-01-09 03:10:30',
                'icon' => NULL,
                'id' => 39,
                'is_menu' => 1,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'driver_details',
                'sort' => 1704778830,
                'title' => 'تعیین مشخصات راننده',
                'updated_at' => '2024-01-09 03:10:30',
            ),
            31 => 
            array (
                'created_at' => '2024-01-09 03:12:45',
                'icon' => NULL,
                'id' => 41,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '39',
                'slug' => 'fuel_type',
                'sort' => 1704778965,
                'title' => 'انواع سوخت',
                'updated_at' => '2024-01-09 03:12:45',
            ),
            32 => 
            array (
                'created_at' => '2024-01-09 03:14:20',
                'icon' => NULL,
                'id' => 42,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '39',
                'slug' => 'certificates_types',
                'sort' => 1704779060,
                'title' => 'انواع گواهینامه',
                'updated_at' => '2024-01-09 03:14:20',
            ),
            33 => 
            array (
                'created_at' => '2024-01-21 07:18:41',
                'icon' => NULL,
                'id' => 43,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'transaction_types',
                'sort' => 1705817921,
                'title' => 'انواع تراکنش',
                'updated_at' => '2024-02-28 06:00:48',
            ),
            34 => 
            array (
                'created_at' => '2024-01-21 07:42:38',
                'icon' => NULL,
                'id' => 44,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'commission',
                'sort' => 1705819358,
                'title' => 'کمیسیون',
                'updated_at' => '2024-01-21 07:51:00',
            ),
            35 => 
            array (
                'created_at' => '2024-01-21 07:43:17',
                'icon' => NULL,
                'id' => 45,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'level',
                'sort' => 1705819397,
                'title' => 'انواع سطح',
                'updated_at' => '2024-01-21 07:43:17',
            ),
            36 => 
            array (
                'created_at' => '2024-01-24 05:28:13',
                'icon' => NULL,
                'id' => 46,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'cancel_driver',
                'sort' => 1706070493,
                'title' => 'الطلبات الملغية من قبل السائق',
                'updated_at' => '2024-10-15 16:46:20',
            ),
            37 => 
            array (
                'created_at' => '2024-01-29 05:33:55',
                'icon' => NULL,
                'id' => 47,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'info_bank',
                'sort' => 1706502835,
                'title' => 'اطلاعات بانکی',
                'updated_at' => '2024-01-29 05:33:55',
            ),
            38 => 
            array (
                'created_at' => '2024-01-29 07:10:12',
                'icon' => NULL,
                'id' => 48,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'banks',
                'sort' => 1706508612,
                'title' => 'بانک ها',
                'updated_at' => '2024-01-29 07:11:43',
            ),
            39 => 
            array (
                'created_at' => '2024-01-31 06:55:28',
                'icon' => NULL,
                'id' => 49,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'services_type',
                'sort' => 1706680528,
                'title' => 'انواع سرویس',
                'updated_at' => '2024-01-31 06:55:28',
            ),
            40 => 
            array (
                'created_at' => '2024-02-06 07:09:40',
                'icon' => NULL,
                'id' => 50,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'equipment_detail',
                'sort' => 1707199780,
                'title' => 'جزئیات وسایل',
                'updated_at' => '2024-02-06 07:09:40',
            ),
            41 => 
            array (
                'created_at' => '2024-02-06 08:12:52',
                'icon' => NULL,
                'id' => 51,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'floor_detail',
                'sort' => 1707203572,
                'title' => 'جزئیات طبقات',
                'updated_at' => '2024-02-06 08:12:52',
            ),
            42 => 
            array (
                'created_at' => '2024-02-21 07:11:38',
                'icon' => NULL,
                'id' => 52,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'gift_cart',
                'sort' => 1708495898,
                'title' => 'تخفیف',
                'updated_at' => '2024-02-21 07:11:38',
            ),
            43 => 
            array (
                'created_at' => '2024-02-21 13:13:48',
                'icon' => NULL,
                'id' => 53,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'state_driver',
                'sort' => 1708517628,
                'title' => 'وضعیت راننده',
                'updated_at' => '2024-02-21 13:13:48',
            ),
            44 => 
            array (
                'created_at' => '2024-02-27 08:03:04',
                'icon' => NULL,
                'id' => 54,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'repetitive_routes',
                'sort' => 1709017384,
                'title' => 'مسیرهای پر تکرار',
                'updated_at' => '2024-02-27 08:19:30',
            ),
            45 => 
            array (
                'created_at' => '2024-02-28 08:32:23',
                'icon' => NULL,
                'id' => 55,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'prefixes',
                'sort' => 1709105543,
                'title' => 'پیش شماره ها',
                'updated_at' => '2024-02-28 08:32:23',
            ),
            46 => 
            array (
                'created_at' => '2024-02-28 11:08:23',
                'icon' => NULL,
                'id' => 56,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'admin_numbers',
                'sort' => 1709114903,
                'title' => 'شماره داخلی ادمین ها',
                'updated_at' => '2024-02-28 11:08:23',
            ),
            47 => 
            array (
                'created_at' => '2024-03-04 03:10:33',
                'icon' => NULL,
                'id' => 57,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'repetitive_place',
                'sort' => 1709530833,
                'title' => 'مسیر پر تکرار',
                'updated_at' => '2024-03-04 03:10:33',
            ),
            48 => 
            array (
                'created_at' => '2024-03-10 06:32:27',
                'icon' => NULL,
                'id' => 58,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'voip',
                'sort' => 1710061347,
                'title' => 'تنظیمات voip',
                'updated_at' => '2024-03-10 06:32:27',
            ),
            49 => 
            array (
                'created_at' => '2024-04-16 06:32:21',
                'icon' => NULL,
                'id' => 60,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '69',
                'slug' => 'rate',
                'sort' => 1713245541,
                'title' => 'امتیاز',
                'updated_at' => '2024-06-22 11:14:35',
            ),
            50 => 
            array (
                'created_at' => '2024-04-22 08:02:33',
                'icon' => NULL,
                'id' => 61,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => NULL,
                'slug' => 'price_detail',
                'sort' => 1713769353,
                'title' => 'جزئیات قیمت',
                'updated_at' => '2024-04-22 08:02:33',
            ),
            51 => 
            array (
                'created_at' => '2024-05-11 05:52:37',
                'icon' => NULL,
                'id' => 62,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'state_completed',
                'sort' => 1715403157,
                'title' => 'وضعیت های تایید مدارک',
                'updated_at' => '2024-05-11 05:52:37',
            ),
            52 => 
            array (
                'created_at' => '2024-05-13 06:51:12',
                'icon' => NULL,
                'id' => 63,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'support',
                'sort' => 1715579472,
                'title' => 'اطلاعات پشتیبانی',
                'updated_at' => '2024-05-13 06:51:12',
            ),
            53 => 
            array (
                'created_at' => '2024-05-13 06:54:48',
                'icon' => NULL,
                'id' => 64,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'questions',
                'sort' => 1715579688,
                'title' => 'سوالات متداول',
                'updated_at' => '2024-05-13 06:54:48',
            ),
            54 => 
            array (
                'created_at' => '2024-05-15 06:35:30',
                'icon' => NULL,
                'id' => 65,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'terms_and_conditions',
                'sort' => 1715751330,
                'title' => 'قوانین و مقررات',
                'updated_at' => '2024-05-15 06:35:30',
            ),
            55 => 
            array (
                'created_at' => '2024-06-05 05:31:04',
                'icon' => NULL,
                'id' => 66,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'limit',
                'sort' => 1717561864,
                'title' => 'محدوده',
                'updated_at' => '2024-06-05 05:31:04',
            ),
            56 => 
            array (
                'created_at' => '2024-06-06 06:28:50',
                'icon' => NULL,
                'id' => 67,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'test',
                'sort' => 1717651730,
                'title' => 'test',
                'updated_at' => '2024-06-06 06:28:50',
            ),
            57 => 
            array (
                'created_at' => '2024-06-22 05:11:16',
                'icon' => NULL,
                'id' => 68,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => NULL,
                'slug' => 'rate_user',
                'sort' => 1719029476,
                'title' => 'امتیاز کاربر',
                'updated_at' => '2024-06-22 05:11:16',
            ),
            58 => 
            array (
                'created_at' => '2024-06-22 11:11:17',
                'icon' => NULL,
                'id' => 69,
                'is_menu' => 1,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'manage_rate',
                'sort' => 1719051077,
                'title' => 'مدیریت امتیاز ها',
                'updated_at' => '2024-06-22 11:11:17',
            ),
            59 => 
            array (
                'created_at' => '2024-06-22 11:14:14',
                'icon' => NULL,
                'id' => 70,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '69',
                'slug' => 'condition_rate',
                'sort' => 1719051254,
                'title' => 'نرخ امتیاز بر اساس مبلغ سفارش',
                'updated_at' => '2024-06-22 11:14:14',
            ),
            60 => 
            array (
                'created_at' => '2024-07-27 10:29:02',
                'icon' => NULL,
                'id' => 73,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'agency_admin',
                'sort' => 1722072542,
                'title' => 'مدیریت آژانس',
                'updated_at' => '2024-07-27 10:29:02',
            ),
            61 => 
            array (
                'created_at' => '2024-07-28 06:57:55',
                'icon' => NULL,
                'id' => 74,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'driver_agency',
                'sort' => 1722146275,
                'title' => 'تعیین راننده آژانس',
                'updated_at' => '2024-07-28 06:57:55',
            ),
            62 => 
            array (
                'created_at' => '2024-07-31 11:20:22',
                'icon' => NULL,
                'id' => 76,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'accepted_order',
                'sort' => 1722421222,
                'title' => 'سفرهای تایید شده',
                'updated_at' => '2024-07-31 11:20:22',
            ),
            63 => 
            array (
                'created_at' => '2024-07-31 11:30:03',
                'icon' => NULL,
                'id' => 77,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'rejected_order',
                'sort' => 1722421803,
                'title' => 'سفرهای رد شده',
                'updated_at' => '2024-07-31 11:30:03',
            ),
            64 => 
            array (
                'created_at' => '2024-08-03 09:50:57',
                'icon' => NULL,
                'id' => 78,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'wallet_admin',
                'sort' => 1722675057,
                'title' => 'کیف پول ادمین',
                'updated_at' => '2024-08-03 09:50:57',
            ),
            65 => 
            array (
                'created_at' => '2024-08-03 09:56:28',
                'icon' => NULL,
                'id' => 79,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'financial_report',
                'sort' => 1722675388,
                'title' => 'گزارشات مالی',
                'updated_at' => '2024-08-03 09:56:28',
            ),
            66 => 
            array (
                'created_at' => '2024-08-03 10:34:39',
                'icon' => NULL,
                'id' => 80,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'wallet_agency',
                'sort' => 1722677679,
                'title' => 'کیف پول آژانس',
                'updated_at' => '2024-08-03 10:34:39',
            ),
            67 => 
            array (
                'created_at' => '2024-08-03 11:17:08',
                'icon' => NULL,
                'id' => 81,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'financial_report_agency',
                'sort' => 1722680228,
                'title' => 'گزارشات مالی آژانس',
                'updated_at' => '2024-08-03 11:17:08',
            ),
            68 => 
            array (
                'created_at' => '2024-08-04 07:08:04',
                'icon' => NULL,
                'id' => 82,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'request_order',
                'sort' => 1722751684,
                'title' => 'درخواست های سفر',
                'updated_at' => '2024-08-04 07:08:04',
            ),
            69 => 
            array (
                'created_at' => '2024-08-10 11:43:57',
                'icon' => NULL,
                'id' => 83,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'discount_order',
                'sort' => 1723286637,
                'title' => 'سفارشات تخفیفی',
                'updated_at' => '2024-08-10 11:43:57',
            ),
            70 => 
            array (
                'created_at' => '2024-08-20 06:19:54',
                'icon' => NULL,
                'id' => 84,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'generate_code',
                'sort' => 1724131194,
                'title' => 'توليد الأكواد مستخدم',
                'updated_at' => '2024-09-18 12:10:09',
            ),
            71 => 
            array (
                'created_at' => '2024-08-20 06:20:27',
                'icon' => NULL,
                'id' => 85,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => NULL,
                'slug' => 'info_code',
                'sort' => 1724131227,
                'title' => 'معلومات رمز الرصید المستخدم',
                'updated_at' => '2024-09-18 12:18:21',
            ),
            72 => 
            array (
                'created_at' => '2024-09-18 11:28:17',
                'icon' => NULL,
                'id' => 86,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'account_check',
                'sort' => 1726655297,
                'title' => 'التحقق من حسابات السائقين',
                'updated_at' => '2024-09-18 11:28:17',
            ),
            73 => 
            array (
                'created_at' => '2024-09-18 12:10:59',
                'icon' => NULL,
                'id' => 87,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'generate_code_driver',
                'sort' => 1726657859,
                'title' => 'توليد الأكواد السائق',
                'updated_at' => '2024-09-18 12:10:59',
            ),
            74 => 
            array (
                'created_at' => '2024-09-18 12:18:56',
                'icon' => NULL,
                'id' => 88,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => NULL,
                'slug' => 'info_code_driver',
                'sort' => 1726658336,
                'title' => 'معلومات رمز الرصید السائق',
                'updated_at' => '2024-09-18 12:18:56',
            ),
            75 => 
            array (
                'created_at' => '2024-09-28 06:37:01',
                'icon' => NULL,
                'id' => 89,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'gender',
                'sort' => 1727503621,
                'title' => 'الجنس',
                'updated_at' => '2024-10-15 16:26:43',
            ),
            76 => 
            array (
                'created_at' => '2024-10-09 11:09:35',
                'icon' => NULL,
                'id' => 91,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'admin_message',
                'sort' => 1728470375,
                'title' => 'رسالة الادمن للسائق',
                'updated_at' => '2024-10-15 16:28:10',
            ),
            77 => 
            array (
                'created_at' => '2024-10-14 11:08:46',
                'icon' => NULL,
                'id' => 92,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'minimum_price_driver',
                'sort' => 1728902326,
                'title' => 'حد الاقصى لديون السائق',
                'updated_at' => '2024-10-15 16:26:27',
            ),
            78 => 
            array (
                'created_at' => '2024-12-04 11:20:18',
                'icon' => NULL,
                'id' => 93,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => '0',
                'slug' => 'service_place_repitive',
                'sort' => 1733309418,
                'title' => 'سرویس مسیر های پرتکرار',
                'updated_at' => '2024-12-04 11:20:18',
            ),
            79 => 
            array (
                'created_at' => '2024-12-11 12:38:07',
                'icon' => NULL,
                'id' => 94,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'drivers_send',
                'sort' => 1733918887,
                'title' => 'drivers_send',
                'updated_at' => '2024-12-11 12:38:07',
            ),
            80 => 
            array (
                'created_at' => '2025-03-02 12:35:49',
                'icon' => NULL,
                'id' => 96,
                'is_menu' => 0,
                'logic_delete' => 1,
                'parent_id' => '0',
                'slug' => 'message',
                'sort' => 1740917149,
                'title' => 'پیام ها',
                'updated_at' => '2025-03-02 12:35:49',
            ),
            81 => 
            array (
                'created_at' => '2025-03-10 10:51:53',
                'icon' => NULL,
                'id' => 101,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'taxi_options',
                'sort' => 1741602113,
                'title' => 'آپشن های سواری',
                'updated_at' => '2025-03-10 10:51:53',
            ),
            82 => 
            array (
                'created_at' => '2025-03-15 09:08:34',
                'icon' => NULL,
                'id' => 102,
                'is_menu' => 0,
                'logic_delete' => 0,
                'parent_id' => NULL,
                'slug' => 'stop_without_driver',
                'sort' => 1742027914,
                'title' => 'آیتم توقف بدون راننده',
                'updated_at' => '2025-03-15 09:08:34',
            ),
        ));
        
        
    }
}